name: Run Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Cache pip dependencies
        id: cache
        uses: actions/cache@v1
        env: 
          cache-name: cache-python-dependencies
        with: 
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install flake8
          pip install -r requirements.txt
          pip install -e .

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          # error codes shown by `--select` can be found
          # here (F): https://flake8.pycqa.org/en/latest/user/error-codes.html
          # and here (E): https://pycodestyle.pycqa.org/en/latest/intro.html#error-codes
          flake8 . --select=E9,F63,F7,F82

      - name: Test with pytest
        run: |
          pytest
